[profile.default]
src = "src"
out = "out"
solc_version = "0.8.29"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
auto_detect_solc = true

libs = ["lib"]

remappings = [
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts-ccip/=lib/ccip/contracts/",
  "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
]

viaIR= true

[rpc_endpoints]
xrplevm = "${XRPL_TESTNET_RPC_URL}"
apothem = "${XDC_TESTNET_RPC_URL}"




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
